# -*- coding: utf-8 -*-
"""신입생세미나파이썬

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N01jgD1tVpsHE2Ax04DivvWF_45R3p3c

2025-22900 통계학과 장윤서
"""

import numpy as np
import matplotlib.pyplot as plt

def plot_trapped_water(height):
    h = np.array(height)
    max_left  = np.maximum.accumulate(h)
    max_right = np.maximum.accumulate(h[::-1])[::-1]

    water = np.clip(np.minimum(max_left, max_right) - h, 0, None)

    idx = np.arange(len(h))
    fig, ax = plt.subplots(figsize=(8, 4))

    ax.bar(idx, h,      color='black', label='Ground')
    ax.bar(idx, water,  bottom=h, color='blue',  label='Water')

    ax.set_xlabel('Index')
    ax.set_ylabel('Height')
    ax.legend()

    plt.tight_layout()
    plt.show()

# ex1
height1 = [2, 0, 2]
#ex2
height2 = [3, 0, 0, 2, 0, 4]
#ex3
height3 = [0, 1, 3, 1, 0, 2, 1, 2, 1, 0, 1]

# 그림 예시
plot_trapped_water(height1)
plot_trapped_water(height2)
plot_trapped_water(height3)